"""Tests for Config Generation — spec 28 (45 tests).

Covers:
  28a — rbac.yaml generator (12 tests)
  28b — limits.yaml generator (8 tests)
  28c — Policy pack templates (10 tests)
  28d — policy.yaml generator (7 tests)
  28e — Generation API (8 tests)
"""

from __future__ import annotations

import io
import uuid
import zipfile

import pytest
import yaml
from httpx import ASGITransport, AsyncClient

from src.main import app
from src.wizard.seed import (
    REFERENCE_AGENT,
    seed_reference_agent,
    seed_reference_tools_and_roles,
)
from src.wizard.services.policy_packs import (
    get_policy_pack,
    list_policy_packs,
)


@pytest.fixture
async def client():
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        yield ac


# ── Helpers ──────────────────────────────────────────────────────────────

_AGENT_BODY = {
    "name": f"ConfigTestAgent-{uuid.uuid4().hex[:8]}",
    "description": "Agent for config gen tests",
    "team": "platform",
    "framework": "langgraph",
    "environment": "dev",
    "is_public_facing": False,
    "has_tools": True,
    "has_write_actions": False,
    "touches_pii": False,
    "handles_secrets": False,
    "calls_external_apis": False,
}


async def _create_agent(client: AsyncClient, **overrides) -> dict:
    body = {**_AGENT_BODY, "name": f"CfgAgent-{uuid.uuid4().hex[:8]}", **overrides}
    resp = await client.post("/v1/agents", json=body)
    assert resp.status_code == 201
    return resp.json()


async def _create_tool(client: AsyncClient, agent_id: str, **overrides) -> dict:
    body = {"name": f"tool-{uuid.uuid4().hex[:8]}", "description": "test", **overrides}
    resp = await client.post(f"/v1/agents/{agent_id}/tools", json=body)
    assert resp.status_code == 201, resp.text
    return resp.json()


async def _create_role(client: AsyncClient, agent_id: str, **overrides) -> dict:
    body = {"name": f"role-{uuid.uuid4().hex[:8]}", "description": "test", **overrides}
    resp = await client.post(f"/v1/agents/{agent_id}/roles", json=body)
    assert resp.status_code == 201, resp.text
    return resp.json()


async def _seed_ref_agent(client: AsyncClient) -> dict:
    """Seed reference agent + tools/roles, return agent dict."""
    await seed_reference_agent()
    await seed_reference_tools_and_roles()
    resp = await client.get("/v1/agents", params={"status": "active"})
    ref = next(a for a in resp.json()["items"] if a["name"] == REFERENCE_AGENT["name"])
    # Set policy_pack on reference agent
    await client.patch(f"/v1/agents/{ref['id']}", json={"policy_pack": "customer_support"})
    return ref


# ═══════════════════════════════════════════════════════════════════════
# 28a — rbac.yaml generator (12 tests)
# ═══════════════════════════════════════════════════════════════════════


@pytest.mark.asyncio
async def test_rbac_generates_valid_yaml(client):
    """Output is parseable YAML."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["rbac_yaml"])
    assert "roles" in data


@pytest.mark.asyncio
async def test_rbac_metadata_header(client):
    """Output contains agent name, ID, timestamp in comments."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    rbac = resp.json()["rbac_yaml"]
    assert "Generated by AI Protector" in rbac
    assert ref["name"] in rbac
    assert str(ref["id"]) in rbac


@pytest.mark.asyncio
async def test_rbac_roles_present(client):
    """All DB roles appear in YAML."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["rbac_yaml"])
    assert set(data["roles"].keys()) == {"user", "admin"}


@pytest.mark.asyncio
async def test_rbac_tools_present(client):
    """All DB tools appear under correct roles."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["rbac_yaml"])
    user_tools = set(data["roles"]["user"]["tools"].keys())
    assert "getOrders" in user_tools
    assert "searchProducts" in user_tools


@pytest.mark.asyncio
async def test_rbac_inheritance_chain(client):
    """inherits field matches DB inheritance."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["rbac_yaml"])
    assert "inherits" not in data["roles"]["user"]
    assert data["roles"]["admin"]["inherits"] == "user"


@pytest.mark.asyncio
async def test_rbac_roles_sorted_by_depth(client):
    """Base roles before child roles in output."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["rbac_yaml"])
    role_names = list(data["roles"].keys())
    assert role_names.index("user") < role_names.index("admin")


@pytest.mark.asyncio
async def test_rbac_scopes_correct(client):
    """read/write scopes match DB access_type."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["rbac_yaml"])
    # updateOrder is write → scopes should include write
    admin_tools = data["roles"]["admin"]["tools"]
    assert "write" in admin_tools["updateOrder"]["scopes"]


@pytest.mark.asyncio
async def test_rbac_sensitivity_correct(client):
    """Sensitivity values match DB."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["rbac_yaml"])
    assert data["roles"]["user"]["tools"]["getOrders"]["sensitivity"] == "low"
    assert data["roles"]["admin"]["tools"]["updateUser"]["sensitivity"] == "high"


@pytest.mark.asyncio
async def test_rbac_confirmation_flag(client):
    """requires_confirmation=true where DB says so."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["rbac_yaml"])
    assert data["roles"]["admin"]["tools"]["updateOrder"].get("requires_confirmation") is True


@pytest.mark.asyncio
async def test_rbac_matches_existing_config(client):
    """Demo agent output matches existing rbac_config.yaml semantically."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    generated = yaml.safe_load(resp.json()["rbac_yaml"])

    # Semantic comparison: same roles, same tools per role, same scopes
    assert set(generated["roles"].keys()) == {"user", "admin"}
    assert generated["roles"]["admin"]["inherits"] == "user"
    # user has getOrders + searchProducts
    assert set(generated["roles"]["user"]["tools"].keys()) == {
        "getOrders",
        "searchProducts",
    }
    # admin has getUsers + updateOrder + updateUser
    assert set(generated["roles"]["admin"]["tools"].keys()) == {
        "getUsers",
        "updateOrder",
        "updateUser",
    }


@pytest.mark.asyncio
async def test_rbac_empty_tools(client):
    """Agent with 0 tools → valid YAML with empty roles."""
    agent = await _create_agent(client)
    await _create_role(client, agent["id"])
    resp = await client.post(f"/v1/agents/{agent['id']}/generate-config")
    data = yaml.safe_load(resp.json()["rbac_yaml"])
    assert "roles" in data


@pytest.mark.asyncio
async def test_rbac_circular_inheritance_error(client):
    """Circular inheritance → error, not infinite loop."""
    # This is prevented at create/update time, but test the generator's
    # safety - it should raise ValueError via _sort_roles_by_depth
    # We can't easily create circular data via API (it's blocked),
    # so we test the function directly
    from unittest.mock import MagicMock

    from src.wizard.services.config_gen import _sort_roles_by_depth

    role_a = MagicMock()
    role_a.id = uuid.uuid4()
    role_a.name = "A"
    role_b = MagicMock()
    role_b.id = uuid.uuid4()
    role_b.name = "B"

    role_a.parent = role_b
    role_a.inherits_from = role_b.id
    role_b.parent = role_a
    role_b.inherits_from = role_a.id

    with pytest.raises(ValueError, match="[Cc]ircular"):
        _sort_roles_by_depth([role_a, role_b])


# ═══════════════════════════════════════════════════════════════════════
# 28b — limits.yaml generator (8 tests)
# ═══════════════════════════════════════════════════════════════════════


@pytest.mark.asyncio
async def test_limits_generates_valid_yaml(client):
    """Output is parseable YAML."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["limits_yaml"])
    assert "roles" in data


@pytest.mark.asyncio
async def test_limits_all_roles_present(client):
    """Every role has budget entry."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["limits_yaml"])
    assert set(data["roles"].keys()) == {"user", "admin"}


@pytest.mark.asyncio
async def test_limits_defaults_from_pack(client):
    """Default values match policy pack tier."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["limits_yaml"])
    pack = get_policy_pack("customer_support")
    # user is depth 0 → "low" tier
    low_tier = pack.limit_tiers["low"]
    assert data["roles"]["user"]["max_tool_calls_per_session"] == low_tier.max_tool_calls_per_session
    assert data["roles"]["user"]["max_cost_usd"] == low_tier.max_cost_usd


@pytest.mark.asyncio
async def test_limits_override_single_value(client):
    """Override max_cost_usd via generate_limits_yaml → only that changes."""
    from src.db.session import get_db
    from src.wizard.services.config_gen import generate_limits_yaml

    ref = await _seed_ref_agent(client)
    async for db in get_db():
        normal = yaml.safe_load(await generate_limits_yaml(uuid.UUID(ref["id"]), db))
        overridden = yaml.safe_load(
            await generate_limits_yaml(
                uuid.UUID(ref["id"]),
                db,
                overrides={"user": {"max_cost_usd": 99.0}},
            )
        )
        assert overridden["roles"]["user"]["max_cost_usd"] == 99.0
        # Other values unchanged
        assert (
            overridden["roles"]["user"]["max_tool_calls_per_session"]
            == normal["roles"]["user"]["max_tool_calls_per_session"]
        )
        break


@pytest.mark.asyncio
async def test_limits_per_tool_rate_limits(client):
    """Tool-level rate_limit appears in output."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["limits_yaml"])
    assert "tool_rate_limits" in data
    # All 5 seeded tools have rate_limits from smart defaults
    assert len(data["tool_rate_limits"]) > 0


@pytest.mark.asyncio
async def test_limits_different_packs(client):
    """customer_support vs research → different default budgets."""
    agent_cs = await _create_agent(client, policy_pack="customer_support")
    agent_r = await _create_agent(client, policy_pack="research")

    # Add a role to each
    await _create_role(client, agent_cs["id"])
    await _create_role(client, agent_r["id"])

    resp_cs = await client.post(f"/v1/agents/{agent_cs['id']}/generate-config")
    resp_r = await client.post(f"/v1/agents/{agent_r['id']}/generate-config")

    limits_cs = yaml.safe_load(resp_cs.json()["limits_yaml"])
    limits_r = yaml.safe_load(resp_r.json()["limits_yaml"])

    cs_role = list(limits_cs["roles"].values())[0]
    r_role = list(limits_r["roles"].values())[0]

    # Research packs have higher limits
    assert r_role["max_tool_calls_per_session"] > cs_role["max_tool_calls_per_session"]


@pytest.mark.asyncio
async def test_limits_no_roles(client):
    """Agent with 0 roles → valid YAML (empty)."""
    agent = await _create_agent(client)
    resp = await client.post(f"/v1/agents/{agent['id']}/generate-config")
    data = yaml.safe_load(resp.json()["limits_yaml"])
    assert data["roles"] == {} or data["roles"] is None


@pytest.mark.asyncio
async def test_limits_deterministic(client):
    """Two calls same input → identical output (ignoring timestamp)."""
    ref = await _seed_ref_agent(client)
    resp1 = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    resp2 = await client.post(f"/v1/agents/{ref['id']}/generate-config")

    lim1 = yaml.safe_load(resp1.json()["limits_yaml"])
    lim2 = yaml.safe_load(resp2.json()["limits_yaml"])
    assert lim1 == lim2


# ═══════════════════════════════════════════════════════════════════════
# 28c — Policy pack templates (10 tests)
# ═══════════════════════════════════════════════════════════════════════


@pytest.mark.asyncio
async def test_list_packs_returns_5(client):
    """list_policy_packs() → 5 packs."""
    packs = list_policy_packs()
    assert len(packs) == 5


@pytest.mark.asyncio
async def test_get_pack_customer_support(client):
    """get_policy_pack('customer_support') → has all required fields."""
    pack = get_policy_pack("customer_support")
    assert pack.scanners.injection_threshold == 0.3
    assert pack.scanners.pii_mode == "mask"


@pytest.mark.asyncio
async def test_get_pack_internal_copilot(client):
    """get_policy_pack('internal_copilot') → correct thresholds."""
    pack = get_policy_pack("internal_copilot")
    assert pack.scanners.injection_threshold == 0.5
    assert pack.scanners.toxicity_threshold == 0.8


@pytest.mark.asyncio
async def test_get_pack_finance(client):
    """get_policy_pack('finance') → strict values."""
    pack = get_policy_pack("finance")
    assert pack.scanners.injection_threshold == 0.2
    assert pack.scanners.pii_mode == "block"


@pytest.mark.asyncio
async def test_get_pack_hr(client):
    """get_policy_pack('hr') → strict values, PII=block."""
    pack = get_policy_pack("hr")
    assert pack.scanners.pii_mode == "block"
    assert pack.scanners.toxicity_threshold == 0.3


@pytest.mark.asyncio
async def test_get_pack_research(client):
    """get_policy_pack('research') → lax values, PII=off."""
    pack = get_policy_pack("research")
    assert pack.scanners.pii_mode == "off"
    assert pack.scanners.pii_redaction is False
    assert pack.scanners.secrets_scanning is False


@pytest.mark.asyncio
async def test_get_pack_nonexistent(client):
    """get_policy_pack('xxx') → KeyError."""
    with pytest.raises(KeyError):
        get_policy_pack("xxx")


@pytest.mark.asyncio
async def test_all_packs_have_required_fields(client):
    """Each pack has: scanners, thresholds, limits, redaction."""
    for pack in list_policy_packs():
        d = pack.to_dict()
        assert "scanners" in d
        assert "output_filtering" in d
        assert "confirmation" in d
        assert "limit_tiers" in d
        assert "injection_threshold" in d["scanners"]
        assert "pii_mode" in d["scanners"]


@pytest.mark.asyncio
async def test_pack_thresholds_in_range(client):
    """All thresholds between 0.0 and 1.0."""
    for pack in list_policy_packs():
        assert 0.0 <= pack.scanners.injection_threshold <= 1.0
        assert 0.0 <= pack.scanners.toxicity_threshold <= 1.0


@pytest.mark.asyncio
async def test_pack_dataclass_immutable(client):
    """Frozen dataclass → cannot modify."""
    pack = get_policy_pack("customer_support")
    with pytest.raises(AttributeError):
        pack.name = "hacked"


# ═══════════════════════════════════════════════════════════════════════
# 28d — policy.yaml generator (7 tests)
# ═══════════════════════════════════════════════════════════════════════


@pytest.mark.asyncio
async def test_policy_generates_valid_yaml(client):
    """Output is parseable YAML."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["policy_yaml"])
    assert "scanners" in data


@pytest.mark.asyncio
async def test_policy_values_from_pack(client):
    """customer_support pack → injection_threshold=0.3."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["policy_yaml"])
    assert data["scanners"]["injection_threshold"] == 0.3
    assert data["scanners"]["pii_mode"] == "mask"


@pytest.mark.asyncio
async def test_policy_override_single_value(client):
    """Override toxicity_threshold → only that changes."""
    from src.db.session import get_db
    from src.wizard.services.config_gen import generate_policy_yaml

    ref = await _seed_ref_agent(client)
    async for db in get_db():
        normal = yaml.safe_load(await generate_policy_yaml(uuid.UUID(ref["id"]), db))
        overridden = yaml.safe_load(
            await generate_policy_yaml(
                uuid.UUID(ref["id"]),
                db,
                overrides={"toxicity_threshold": 0.99},
            )
        )
        assert overridden["scanners"]["toxicity_threshold"] == 0.99
        # Other values unchanged
        assert overridden["scanners"]["injection_threshold"] == normal["scanners"]["injection_threshold"]
        break


@pytest.mark.asyncio
async def test_policy_all_scanner_toggles(client):
    """All scanner on/off flags present."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["policy_yaml"])
    for key in [
        "injection_detection",
        "pii_redaction",
        "secrets_scanning",
        "toxicity_detection",
        "nemo_guardrails",
    ]:
        assert key in data["scanners"]


@pytest.mark.asyncio
async def test_policy_output_filtering_section(client):
    """output_filtering section present with correct values."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["policy_yaml"])
    assert "output_filtering" in data
    assert "max_output_size" in data["output_filtering"]


@pytest.mark.asyncio
async def test_policy_confirmation_section(client):
    """confirmation section with sensitivity list."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    data = yaml.safe_load(resp.json()["policy_yaml"])
    assert "confirmation" in data
    assert "required_for_sensitivity" in data["confirmation"]
    assert "high" in data["confirmation"]["required_for_sensitivity"]


@pytest.mark.asyncio
async def test_policy_deterministic(client):
    """Two calls same input → identical output (ignoring timestamp)."""
    ref = await _seed_ref_agent(client)
    resp1 = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    resp2 = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    pol1 = yaml.safe_load(resp1.json()["policy_yaml"])
    pol2 = yaml.safe_load(resp2.json()["policy_yaml"])
    assert pol1 == pol2


# ═══════════════════════════════════════════════════════════════════════
# 28e — Generation API (8 tests)
# ═══════════════════════════════════════════════════════════════════════


@pytest.mark.asyncio
async def test_generate_returns_all_3_files(client):
    """POST → response has rbac_yaml, limits_yaml, policy_yaml."""
    ref = await _seed_ref_agent(client)
    resp = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    assert resp.status_code == 200
    data = resp.json()
    assert "rbac_yaml" in data
    assert "limits_yaml" in data
    assert "policy_yaml" in data
    assert "generated_at" in data


@pytest.mark.asyncio
async def test_generate_stores_on_agent(client):
    """After POST, GET /agents/:id/config returns cached config."""
    ref = await _seed_ref_agent(client)
    await client.post(f"/v1/agents/{ref['id']}/generate-config")
    resp = await client.get(f"/v1/agents/{ref['id']}/config")
    assert resp.status_code == 200
    assert "rbac_yaml" in resp.json()


@pytest.mark.asyncio
async def test_generate_nonexistent_agent(client):
    """POST with bad ID → 404."""
    resp = await client.post(f"/v1/agents/{uuid.uuid4()}/generate-config")
    assert resp.status_code == 404


@pytest.mark.asyncio
async def test_generate_agent_no_tools(client):
    """Agent with no tools → valid but minimal config."""
    agent = await _create_agent(client)
    resp = await client.post(f"/v1/agents/{agent['id']}/generate-config")
    assert resp.status_code == 200
    data = yaml.safe_load(resp.json()["rbac_yaml"])
    assert "roles" in data


@pytest.mark.asyncio
async def test_get_config_before_generate(client):
    """GET /agents/:id/config before any generation → 404."""
    agent = await _create_agent(client)
    resp = await client.get(f"/v1/agents/{agent['id']}/config")
    assert resp.status_code == 404


@pytest.mark.asyncio
async def test_download_zip(client):
    """GET /agents/:id/config/download → zip with 3 YAML files."""
    ref = await _seed_ref_agent(client)
    await client.post(f"/v1/agents/{ref['id']}/generate-config")
    resp = await client.get(f"/v1/agents/{ref['id']}/config/download")
    assert resp.status_code == 200
    assert "application/zip" in resp.headers["content-type"]

    buf = io.BytesIO(resp.content)
    with zipfile.ZipFile(buf) as zf:
        names = zf.namelist()
        assert "rbac.yaml" in names
        assert "limits.yaml" in names
        assert "policy.yaml" in names


@pytest.mark.asyncio
async def test_download_zip_valid_yaml(client):
    """Each file in zip is parseable YAML."""
    ref = await _seed_ref_agent(client)
    await client.post(f"/v1/agents/{ref['id']}/generate-config")
    resp = await client.get(f"/v1/agents/{ref['id']}/config/download")

    buf = io.BytesIO(resp.content)
    with zipfile.ZipFile(buf) as zf:
        for name in zf.namelist():
            content = zf.read(name).decode()
            parsed = yaml.safe_load(content)
            assert parsed is not None, f"{name} parsed to None"


@pytest.mark.asyncio
async def test_regenerate_overwrites_cache(client):
    """Generate twice → GET config returns latest."""
    ref = await _seed_ref_agent(client)
    await client.post(f"/v1/agents/{ref['id']}/generate-config")

    # Small delay to ensure different timestamp
    resp2 = await client.post(f"/v1/agents/{ref['id']}/generate-config")
    ts2 = resp2.json()["generated_at"]

    cached = await client.get(f"/v1/agents/{ref['id']}/config")
    assert cached.json()["generated_at"] == ts2
