"""Config generation services (spec 28a, 28b, 28d).

Deterministic generators that produce YAML config files from DB state.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import TYPE_CHECKING

import yaml
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload
from sqlalchemy.orm.attributes import set_committed_value

from src.wizard.models import (
    Agent,
    AgentRole,
    AgentTool,
    RoleToolPermission,
)
from src.wizard.services.permissions import resolve_permissions_for_role
from src.wizard.services.policy_packs import get_policy_pack

if TYPE_CHECKING:
    pass


# ═══════════════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════════════


async def _load_agent(agent_id: uuid.UUID, db: AsyncSession) -> Agent:
    agent = await db.get(Agent, agent_id)
    if agent is None:
        raise ValueError(f"Agent {agent_id} not found")
    return agent


async def _load_tools(agent_id: uuid.UUID, db: AsyncSession) -> list[AgentTool]:
    result = await db.execute(select(AgentTool).where(AgentTool.agent_id == agent_id).order_by(AgentTool.name))
    return list(result.scalars().all())


async def _load_roles_with_chain(agent_id: uuid.UUID, db: AsyncSession) -> list[AgentRole]:
    """Load all roles with permissions + manually-wired parent chain."""
    result = await db.execute(
        select(AgentRole)
        .where(AgentRole.agent_id == agent_id)
        .options(
            selectinload(AgentRole.permissions).selectinload(RoleToolPermission.tool),
        )
        .order_by(AgentRole.name)
    )
    roles = list(result.scalars().unique().all())
    role_by_id = {r.id: r for r in roles}
    for role in roles:
        parent = role_by_id.get(role.inherits_from) if role.inherits_from else None
        set_committed_value(role, "parent", parent)
    return roles


def _sort_roles_by_depth(roles: list[AgentRole]) -> list[AgentRole]:
    """Sort roles so base roles (no parent) come first, then children."""
    depth: dict[uuid.UUID, int] = {}

    def _get_depth(role: AgentRole, visited: set[uuid.UUID] | None = None) -> int:
        if visited is None:
            visited = set()
        if role.id in visited:
            raise ValueError(f"Circular inheritance detected involving role '{role.name}'")
        if role.id in depth:
            return depth[role.id]
        visited.add(role.id)
        if role.parent is None:
            depth[role.id] = 0
        else:
            depth[role.id] = _get_depth(role.parent, visited) + 1
        return depth[role.id]

    for r in roles:
        _get_depth(r)

    return sorted(roles, key=lambda r: (depth.get(r.id, 0), r.name))


def _metadata_header(agent: Agent, extra: str = "") -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# Generated by AI Protector for: {agent.name}",
        f"# Generated at: {now}",
        f"# Agent ID: {agent.id}",
    ]
    if extra:
        lines.append(f"# {extra}")
    lines.append("")
    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════
# 28a — rbac.yaml generator
# ═══════════════════════════════════════════════════════════════════════


async def generate_rbac_yaml(agent_id: uuid.UUID, db: AsyncSession) -> str:
    """Generate rbac.yaml from DB state.

    Roles are sorted by inheritance depth (base first).
    Each role lists only its own tools; inheritance is expressed
    via the `inherits` key.
    """
    agent = await _load_agent(agent_id, db)
    roles = await _load_roles_with_chain(agent_id, db)
    sorted_roles = _sort_roles_by_depth(roles)

    header = _metadata_header(agent)

    roles_dict: dict = {}
    for role in sorted_roles:
        role_entry: dict = {}

        if role.parent is not None:
            role_entry["inherits"] = role.parent.name

        own_perms, _ = resolve_permissions_for_role(role)
        tools_dict: dict = {}
        for perm in own_perms:
            tool = perm.tool
            if tool is None:
                continue
            tool_entry: dict = {
                "scopes": perm.scopes,
                "sensitivity": tool.sensitivity.value,
            }
            if tool.requires_confirmation:
                tool_entry["requires_confirmation"] = True
            tools_dict[tool.name] = tool_entry

        role_entry["tools"] = tools_dict
        roles_dict[role.name] = role_entry

    body = yaml.dump(
        {"roles": roles_dict},
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )

    return header + body


# ═══════════════════════════════════════════════════════════════════════
# 28b — limits.yaml generator
# ═══════════════════════════════════════════════════════════════════════

# Role → tier mapping based on inheritance depth
_DEPTH_TO_TIER = {0: "low", 1: "medium", 2: "high"}


async def generate_limits_yaml(
    agent_id: uuid.UUID,
    db: AsyncSession,
    overrides: dict | None = None,
) -> str:
    """Generate limits.yaml with per-role budgets.

    Tier assignment: depth 0 → low, depth 1 → medium, depth 2+ → high.
    Defaults come from the agent's policy pack.
    """
    agent = await _load_agent(agent_id, db)
    roles = await _load_roles_with_chain(agent_id, db)
    tools = await _load_tools(agent_id, db)
    sorted_roles = _sort_roles_by_depth(roles)
    overrides = overrides or {}

    pack_name = agent.policy_pack or "customer_support"
    try:
        pack = get_policy_pack(pack_name)
    except KeyError:
        pack = get_policy_pack("customer_support")

    header = _metadata_header(agent, f"Policy pack: {pack_name}")

    # Compute depth for tier mapping
    depth: dict[uuid.UUID, int] = {}

    def _calc_depth(role: AgentRole) -> int:
        if role.id in depth:
            return depth[role.id]
        if role.parent is None:
            depth[role.id] = 0
        else:
            depth[role.id] = _calc_depth(role.parent) + 1
        return depth[role.id]

    for r in sorted_roles:
        _calc_depth(r)

    roles_dict: dict = {}
    for role in sorted_roles:
        d = depth.get(role.id, 0)
        tier_name = _DEPTH_TO_TIER.get(d, "high")
        tier = pack.limit_tiers.get(tier_name, pack.limit_tiers.get("low"))
        if tier is None:
            from src.wizard.services.policy_packs import LOW_TIER

            tier = LOW_TIER

        role_limits = {
            "max_tool_calls_per_session": tier.max_tool_calls_per_session,
            "max_tokens_in": tier.max_tokens_in,
            "max_tokens_out": tier.max_tokens_out,
            "max_cost_usd": tier.max_cost_usd,
        }

        # Apply per-role overrides
        role_overrides = overrides.get(role.name, {})
        role_limits.update(role_overrides)

        roles_dict[role.name] = role_limits

    # Per-tool rate limits
    tool_limits: dict = {}
    for tool in tools:
        if tool.rate_limit is not None:
            tool_limits[tool.name] = {"rate_limit_per_session": tool.rate_limit}

    data: dict = {"roles": roles_dict}
    if tool_limits:
        data["tool_rate_limits"] = tool_limits

    body = yaml.dump(
        data,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )

    return header + body


# ═══════════════════════════════════════════════════════════════════════
# 28d — policy.yaml generator
# ═══════════════════════════════════════════════════════════════════════


async def generate_policy_yaml(
    agent_id: uuid.UUID,
    db: AsyncSession,
    overrides: dict | None = None,
) -> str:
    """Generate policy.yaml from the agent's policy pack + overrides."""
    agent = await _load_agent(agent_id, db)
    overrides = overrides or {}

    pack_name = agent.policy_pack or "customer_support"
    try:
        pack = get_policy_pack(pack_name)
    except KeyError:
        pack = get_policy_pack("customer_support")

    header = _metadata_header(agent, f"Policy pack: {pack_name}")

    scanners = {
        "injection_detection": pack.scanners.injection_detection,
        "injection_threshold": pack.scanners.injection_threshold,
        "pii_redaction": pack.scanners.pii_redaction,
        "pii_mode": pack.scanners.pii_mode,
        "secrets_scanning": pack.scanners.secrets_scanning,
        "toxicity_detection": pack.scanners.toxicity_detection,
        "toxicity_threshold": pack.scanners.toxicity_threshold,
        "nemo_guardrails": pack.scanners.nemo_guardrails,
    }

    output_filtering = {
        "pii_redaction": pack.output_filtering.pii_redaction,
        "secrets_scanning": pack.output_filtering.secrets_scanning,
        "injection_detection": pack.output_filtering.injection_detection,
        "max_output_size": pack.output_filtering.max_output_size,
    }

    confirmation = {
        "required_for_sensitivity": list(pack.confirmation.required_for_sensitivity),
        "timeout_seconds": pack.confirmation.timeout_seconds,
    }

    data = {
        "scanners": scanners,
        "output_filtering": output_filtering,
        "confirmation": confirmation,
    }

    # Apply overrides (flat keys like "toxicity_threshold")
    for key, value in overrides.items():
        for section in [data["scanners"], data["output_filtering"], data["confirmation"]]:
            if key in section:
                section[key] = value

    body = yaml.dump(
        data,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )

    return header + body
