"""LOCAL MOCK of the wizard-generated security layer — for unit testing only.

In production, the agent does NOT enforce security locally. Instead, it calls
the running AI Protector proxy service over HTTP:
  - PreToolGate  → POST {PROXY_URL}/v1/security/pre-tool-check
  - PostToolGate → POST {PROXY_URL}/v1/security/post-tool-scan
  - Traces, limits, RBAC — all handled server-side by the proxy.

This file simulates the same interface so that unit tests can run without
a live proxy. The real ``protected_agent.py`` generated by the wizard
contains HTTP calls, not local logic.

╔══════════════════════════════════════════════════════════════════╗
║  AI PROTECTOR — Security Layer (Pure Python variant)            ║
║                                                                ║
║  This is the core security module loaded by the agent.          ║
║  Look for sections marked with:                                 ║
║                                                                ║
║    # ═══ AI PROTECTOR ═══                                      ║
║                                                                ║
║  Components:                                                    ║
║    1. SecurityConfig       — loads wizard YAML configs           ║
║    2. check_rbac()         — role-based tool access control      ║
║    3. check_limits()       — rate limit enforcement              ║
║    4. scan_output()        — PII + injection scan (post-tool)    ║
║    5. protected_tool_call()— full pipeline: RBAC→limits→exec→scan║
╚══════════════════════════════════════════════════════════════════╝
"""

from __future__ import annotations

import os
import re
from typing import Any

import yaml

CONFIG_DIR = os.path.join(os.path.dirname(__file__), "config")

# Pre-compiled PII patterns — bounded quantifiers prevent ReDoS on user-controlled input.
_EMAIL_RE = re.compile(
    r"[a-zA-Z0-9][a-zA-Z0-9._%+-]{0,63}@[a-zA-Z0-9][a-zA-Z0-9.-]{0,253}\.[a-zA-Z]{2,6}"
)
_PHONE_RE = re.compile(r"\+?\d[\d\-\s]{5,15}\d")


# ── SecurityConfig ────────────────────────────────────────────────────


# ═══ AI PROTECTOR — SecurityConfig (wizard YAML loader) ═════════
#
# This singleton loads the wizard-generated configuration files:
#   - rbac.yaml   → role permissions, tool access rules
#   - limits.yaml → rate limits, budget constraints
#   - policy.yaml → scanner settings (PII, injection)
#


class SecurityConfig:
    """Loads and holds wizard-generated YAML configs."""

    def __init__(self) -> None:
        self.rbac: dict = {}
        self.limits: dict = {}
        self.policy: dict = {}
        self.loaded = False

    def load_from_files(self, config_dir: str = CONFIG_DIR) -> None:
        """Load RBAC, limits, policy from YAML files in *config_dir*."""
        for name in ("rbac", "limits", "policy"):
            path = os.path.join(config_dir, f"{name}.yaml")
            if os.path.exists(path):
                with open(path) as f:
                    setattr(self, name, yaml.safe_load(f) or {})
        self.loaded = True

    def load_from_kit(self, kit: dict) -> None:
        """Load configs from wizard integration-kit API response."""
        files = kit.get("files", {})
        for name in ("rbac", "limits", "policy"):
            raw = files.get(f"{name}.yaml", "")
            if raw:
                setattr(self, name, yaml.safe_load(raw) or {})
        self.loaded = True

    def load_from_dicts(
        self,
        *,
        rbac: dict | None = None,
        limits: dict | None = None,
        policy: dict | None = None,
    ) -> None:
        """Load configs from plain dicts (useful for tests)."""
        if rbac is not None:
            self.rbac = rbac
        if limits is not None:
            self.limits = limits
        if policy is not None:
            self.policy = policy
        self.loaded = True


_config = SecurityConfig()


def get_config() -> SecurityConfig:
    """Return the singleton config instance."""
    return _config


def reset_config() -> None:
    """Reset config to default (for tests)."""
    global _config  # noqa: PLW0603
    _config = SecurityConfig()


# ═══ AI PROTECTOR — Gate functions ═══════════════════════════════


# ═══ AI PROTECTOR — check_rbac (Role-Based Access Control) ═════
#
# Checks if a given role has permission to call a specific tool.
# Supports role inheritance (e.g. admin inherits from user).
# Reads from rbac.yaml loaded into SecurityConfig.
#
def check_rbac(role: str, tool: str) -> dict[str, Any]:
    """RBAC permission check with inheritance walking."""
    roles = _config.rbac.get("roles", {})
    visited: set[str] = set()
    current: str | None = role
    while current and current not in visited:
        visited.add(current)
        role_cfg = roles.get(current, {})
        tools = role_cfg.get("tools", {})
        if tool in tools:
            t = tools[tool]
            return {
                "allowed": True,
                "scopes": t.get("scopes", ["read"]),
                "requires_confirmation": t.get("requires_confirmation", False),
            }
        current = role_cfg.get("inherits")
    return {"allowed": False, "scopes": [], "requires_confirmation": False}


# ═══ AI PROTECTOR — check_limits (Rate Limits & Budgets) ═══════
#
# Enforces per-role rate limits on tool calls per session.
# Reads max_tool_calls_per_session from limits.yaml.
#
def check_limits(role: str, tool: str) -> dict[str, Any]:
    """Rate limit check (simplified — no server-side counter yet)."""
    role_limits = _config.limits.get("roles", {}).get(role, {})
    max_calls = role_limits.get("max_tool_calls_per_session", 20)
    return {"within_limits": True, "max_calls": max_calls}


# ═══ AI PROTECTOR — scan_output (PII + Injection, runs AFTER tool) ═
#
# Scans tool output for:
#   - PII: email addresses, phone numbers (configurable in policy.yaml)
#   - Injection: SQL injection, prompt injection patterns
# Returns: {clean: bool, findings: [{type, detail}]}
#
def scan_output(output: str) -> dict[str, Any]:
    """Post-tool output scanning: PII detection + injection detection."""
    findings: list[dict] = []
    scanners = _config.policy.get("scanners", {})

    if scanners.get("pii_redaction", True):
        if _EMAIL_RE.search(output):
            findings.append(
                {"type": "pii", "subtype": "email", "detail": "Email address detected"}
            )
        if _PHONE_RE.search(output):
            findings.append(
                {"type": "pii", "subtype": "phone", "detail": "Phone number detected"}
            )

    if scanners.get("injection_detection", True):
        for pattern in [
            "DROP TABLE",
            "DELETE FROM",
            "'; --",
            "UNION SELECT",
            "ignore all previous",
            "you are now",
            "reveal your system",
        ]:
            if pattern.lower() in output.lower():
                findings.append({"type": "injection", "detail": f"Pattern: {pattern}"})

    return {"clean": len(findings) == 0, "findings": findings}


# ═══ AI PROTECTOR — protected_tool_call (Full Security Pipeline) ═
#
# This is the main entry point for securing any tool call.
# It runs the full pipeline:
#   1. RBAC check    → is this role allowed to use this tool?
#   2. Confirmation  → does this tool need explicit user approval?
#   3. Rate limits   → has the role exceeded max calls?
#   4. Execute tool  → run the actual tool function
#   5. Output scan   → check for PII and injection in the result
#
# Usage:
#   result = protected_tool_call(
#       role="user",
#       tool="getOrders",
#       args={},
#       execute_fn=execute_tool,
#   )
#
def protected_tool_call(
    role: str,
    tool: str,
    args: dict | None,
    execute_fn: Any,
) -> dict:
    """Full protection wrapper: RBAC → limits → execute → scan output."""
    # 1. RBAC check
    perm = check_rbac(role, tool)
    if not perm["allowed"]:
        return {
            "allowed": False,
            "result": None,
            "gate": "pre_tool",
            "decision": "block",
            "reason": f"Role '{role}' cannot use '{tool}'",
            "scan_result": None,
        }

    # 2. Confirmation check
    if perm["requires_confirmation"]:
        return {
            "allowed": True,
            "result": None,
            "gate": "pre_tool",
            "decision": "confirm",
            "reason": f"Tool '{tool}' requires confirmation (write, high sensitivity)",
            "requires_confirmation": True,
            "scan_result": None,
        }

    # 3. Limits check
    limit = check_limits(role, tool)
    if not limit["within_limits"]:
        return {
            "allowed": False,
            "result": None,
            "gate": "pre_tool",
            "decision": "block",
            "reason": "Rate limit exceeded",
            "scan_result": None,
        }

    # 4. Execute tool
    result = execute_fn(tool, args or {})

    # 5. Post-tool scan
    scan = scan_output(str(result))

    return {
        "allowed": True,
        "result": result,
        "gate": "post_tool",
        "decision": "allow" if scan["clean"] else "flagged",
        "reason": None if scan["clean"] else "Output contains flagged content",
        "scan_result": scan,
    }
