"""aw_004_agent_generated_kit

Revision ID: d2d2cf58b4c5
Revises: 07ffe5e3695f
Create Date: 2026-03-10 21:57:25.860611

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2d2cf58b4c5"
down_revision: str | Sequence[str] | None = "07ffe5e3695f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("generated_kit", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "generated_kit")
    # ### end Alembic commands ###
