"""aw_002_tools_roles_permissions

Revision ID: f064246659bb
Revises: f7dedf9f10fa
Create Date: 2026-03-10 21:34:49.465637

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f064246659bb"
down_revision: str | Sequence[str] | None = "f7dedf9f10fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_roles",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("inherits_from", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["inherits_from"], ["agent_roles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_roles_agent_id"), "agent_roles", ["agent_id"], unique=False)
    op.create_table(
        "agent_tools",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("access_type", sa.Enum("READ", "WRITE", name="access_type"), nullable=False),
        sa.Column("sensitivity", sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="sensitivity"), nullable=False),
        sa.Column("requires_confirmation", sa.Boolean(), nullable=False),
        sa.Column("arg_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("returns_pii", sa.Boolean(), nullable=False),
        sa.Column("returns_secrets", sa.Boolean(), nullable=False),
        sa.Column("rate_limit", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_tools_agent_id"), "agent_tools", ["agent_id"], unique=False)
    op.create_table(
        "role_tool_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("tool_id", sa.Uuid(), nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requires_confirmation_override", sa.Boolean(), nullable=True),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["agent_roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tool_id"], ["agent_tools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_tool_permissions_role_id"), "role_tool_permissions", ["role_id"], unique=False)
    op.create_index(op.f("ix_role_tool_permissions_tool_id"), "role_tool_permissions", ["tool_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_role_tool_permissions_tool_id"), table_name="role_tool_permissions")
    op.drop_index(op.f("ix_role_tool_permissions_role_id"), table_name="role_tool_permissions")
    op.drop_table("role_tool_permissions")
    op.drop_index(op.f("ix_agent_tools_agent_id"), table_name="agent_tools")
    op.drop_table("agent_tools")
    op.drop_index(op.f("ix_agent_roles_agent_id"), table_name="agent_roles")
    op.drop_table("agent_roles")
    # ### end Alembic commands ###
