"""aw_001 — agents table

Revision ID: f7dedf9f10fa
Revises: c3d4e5f6a7b8
Create Date: 2026-03-10 21:12:50.431781

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7dedf9f10fa"
down_revision: str | Sequence[str] | None = "c3d4e5f6a7b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("team", sa.String(length=64), nullable=True),
        sa.Column(
            "framework", sa.Enum("LANGGRAPH", "RAW_PYTHON", "PROXY_ONLY", name="agent_framework"), nullable=False
        ),
        sa.Column("environment", sa.Enum("DEV", "STAGING", "PRODUCTION", name="agent_environment"), nullable=False),
        sa.Column("is_public_facing", sa.Boolean(), nullable=False),
        sa.Column("has_tools", sa.Boolean(), nullable=False),
        sa.Column("has_write_actions", sa.Boolean(), nullable=False),
        sa.Column("touches_pii", sa.Boolean(), nullable=False),
        sa.Column("handles_secrets", sa.Boolean(), nullable=False),
        sa.Column("calls_external_apis", sa.Boolean(), nullable=False),
        sa.Column("risk_level", sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="risk_level"), nullable=True),
        sa.Column(
            "protection_level", sa.Enum("PROXY_ONLY", "AGENT_RUNTIME", "FULL", name="protection_level"), nullable=True
        ),
        sa.Column("policy_pack", sa.String(length=64), nullable=True),
        sa.Column("rollout_mode", sa.Enum("OBSERVE", "WARN", "ENFORCE", name="rollout_mode"), nullable=False),
        sa.Column("status", sa.Enum("DRAFT", "ACTIVE", "ARCHIVED", name="agent_status"), nullable=False),
        sa.Column("is_reference", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_name"), "agents", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agents_name"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
